#!/bin/bash

listarElementosPapelera() {

	#En esta línea he conseguido que printe el fomato usando AWK pero el problema es que al generar el fichero de restauració.log se añade la ruta antigua o el nombre del fichero
	#Dejo este comentario en caso de que no pueda mejorar más el script de tal forma que en borra.sh consiga funcionar las rutas. Usando el siguiente comando funciona perfectamente pero prinatrá
	#Únicamente la ruta no el nombre del fichero ya que va añadido o bien por ejemplo /home/alfonsodg/prueba1.txt o bien prueba1.txt no he conseguido separa-r ambas rutas

	cat /trash/trashlogs/restauracio.log | awk '{ print $1 "<--" $1 }'
}

informacionFicheroPerdido() {

	echo -n "Introduzca el nombre del fichero que se encuentra dentro del directorio /trash/paperera: "

	read nombreFicheroUser

	echo

	if [[ $# -eq 0 ]]; then

		echo "No has introducido ningún fichero, no procederemos con la información del fichero"

		sleep 1

		echo "Saliendo del programa..."

		exit 1

	elif [[ ! -f $nombreFicheroUser ]]; then

		echo "Lo seinto pero no has introducido un fichero adecuadamente, ha sintroducido $nombreFicheroUser no continuaremos con el programa"

		echo

		sleep 1

		echo "Saliendo del programa..."

		exit 2

	else

		echo "Fichero encontrado correctamente. A continuación te muestro su información"

		sudo file $nombreFicheroUser

		echo

		echo "Información printada correctamente $USER te devuelvo a tu prompt"

	fi

}

restaurarFicheroPapelera() {

	rutaAntiguaFichero=$(cat /trash/trashlogs/trashlog.log | awk '{ print $1 }')

	echo

	echo -n "Introduzca el nombre del fichero que desea restaurar: "

	read ficheroRestaurarUser

	if [[ $# -eq 0 ]]; then

                echo "No has introducido ningún fichero, no procederemos con la información del fichero"

                sleep 1

                echo "Saliendo del programa..."

                exit 1

	elif [[ ! -f $ficheroRestaurarUser ]]; then


		echo "No has seleccionado un fichero adecuado $USER esta acción no ha funcionado"

		echo

		sleep 1

		echo "Saliendo del programa..."

		exit 3

	else

		echo "Hemos encontrado el fichero, lo devolvemos a su ubicación original"

		echo

		echo "Moviendo a su ruta original..."

		sleep 1

		sudo mv $ficheroRestaurarUser $rutaAntiguaFichero
	fi


}

extensionFichero() {

	echo

	echo -n "Introduzca a continuación una extensión de entre las siguientes [.txt, .mp3, .pdf, .tar u otros ejemplos que quiera]: "

	read extensionUser

	ficheroPapeleraPorExtension=$(ls -l /trash/paperera | sed -n '/.\.$extensionUser$/p')

	saberRutaAntiguaFichero=$(cat /trash/trashlogs/restauracio.log | awk '{ print $2 }')

	echo

	echo "Procedemos a vacíar los ficheros pasado por extensión $extensionUser"

	sudo mv $ficheroPapeleraPorExtension $saberRutaAntiguaFichero

}

eliminarFicheroPapelera() {

	echo

	echo -n "Desea eliminar los ficheros que hay actualmente en la papelera de reciclaje [y/n]: "

	read siNoUser

	if [[ $siNoUser == "y" ]]; then

		echo "Perfecto $USER, procedemos a vaciar la papelera de reciclaje"

		echo

		sudo rm -r /trash/paperera/*

	elif [[ $siNoUser == "n" ]]; then

		echo "Vale $USER, pues saldremos del propio programa..."

		echo

		exit 2

	else
		echo

		echo "No has indicado una operación válida. Saliende del programa debido a error"

		exit 3
	fi

}

numeroDiasEliminarContenido() {

	echo "Función no programada. Lo sentimos $USER"

	echo
}

salirProgramaPapelera() {

	echo

	echo "Saliendo del programa MyTrash script"

	echo

	echo "Hasta la vista $USER vuelva cuando quiera"

	exit 4
}
